---
- hosts: k8s-clients
  tasks:
    - name: "create .kube directory"
      file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory

    - name: "Copy admin kube config file to node"
      copy: src="{{ inventory_dir }}/artifacts/admin.conf" dest="/home/{{ ansible_user }}/.kube"
